version: '3.7'

services:
  frontend:
    restart: unless-stopped
    build: .
    image: xmin12/uk-fe
    container_name: jasmin-frontend
    depends_on:
      - backend
    ports:
      - 8916:80
  backend:
    restart: unless-stopped
    image: xmin12/uk-be
    container_name: jasmin-backend
    environment:
      -  jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: jasmin-db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
